ci: Use coreutils shuf instead of devbox shuf
This will hopefully reduce the following errors coming out of devbox

/usr/bin/sh: 1: /home/runner/_work/cluster-api-runtime-extensions-nutanix/cluster-api-runtime-extensions-nutanix/.devbox/gen/scripts/.cmd.sh: Text file busy
Error: error running script "shuf" in Devbox: exit status 126
Error: error running script "fping" in Devbox: exit status 141