build: downgrade clusterctl version (#1330)
**What problem does this PR solve?**:
Newer version fails when running an older CAPI version: 
```
$ clusterctl get kubeconfig $CLUSTER_NAME
Error: this version of clusterctl could be used only with "v1beta2" management clusters, "v1beta1" detected
```

Can switch to latest once
https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/pull/1325
is merged

**Which issue(s) this PR fixes**:
Fixes #

**How Has This Been Tested?**:
<!--
Please describe the tests that you ran to verify your changes.
Provide output from the tests and any manual steps needed to replicate
the tests.
-->

**Special notes for your reviewer**:
<!--
Use this to provide any additional information to the reviewers.
This may include:
- Best way to review the PR.
- Where the author wants the most review attention on.
- etc.
-->